---
- name: manage files/directories
  hosts: all
  connection: winrm
  
  tasks:
  - name: create directory with Ansible module
    win_file:
      path: C:\ansible\ansible-module
      state: directory

  - name: create directory with DSC module
    win_dsc:
      resource_name: File
      type: Directory
      destinationpath: C:\ansible\dsc-module
      ensure: present
